### ISSUE TITLE
Installer

### ISSUE THREAD

**Issue by finn021** [astra1dev/AUnlocker#13]
Hi, I created a draft installer for the unlocker. I wasn't sure how to incorporate it so I made this issue to see whether you wanted to use it in the project or make any changes or anything.
The actual installer .exe can be found in the Output folder and runs standalone. The other files in the .zip are necessary to compile the .exe and the .iss file is the compiler script. The installer is based on the 1.1.4 release files.
[test.installer.zip](https://github.com/user-attachments/files/16189600/test.installer.zip)

Let me know what you want to do, 
Thanks.

**Comment by astra1dev** [comment]
Hi, first of all thanks for your contribution.

However, I don't think an installer is necessary / useful because the installation of AUnlocker is pretty straightforward and it's safer for people to download the mod zip directly from this repo and extract the files than run a "random" (i know its not) exe file.

If you have any further requests please let me know.
